(function(){"use strict";const LIGA=window.LIGA,R=window.RAIZ||"",JUG=LIGA.jugadores,K=LIGA.keys,MET=LIGA.metricas;const KI=Object.fromEntries(K.map((k,i)=>[k,i])),MINPCT=LIGA.params.minPct;const POSN={G:"Arquero",D:"Defensor",M:"Mediocampista",F:"Delantero"},POSP=LIGA.posNombres;const POSA={G:"Arq",D:"Def",M:"Med",F:"Del"};const app=document.getElementById("app");const esc=t=>String(t==null?"":t).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));const escudoChico=ts=>`<img src="${R}datos/escudos/${ts}.webp" alt="" style="width:15px;height:15px;object-fit:contain;vertical-align:-3px;margin-right:4px" onerror="this.remove()">`;const val=(j,k)=>j.v[KI[k]],pct=(j,k)=>j.p[KI[k]];function fmt(k,v){if(v==null)return"–";const f=MET[k].fmt,dec=((f.split(";")[0].split(".")[1])||"").length;let s=Number(v).toFixed(dec);if(f.startsWith("+")&&v>0)s="+"+s;return s+(/Pct$|Share$/.test(k)?"%":"");}
const colorPct=p=>p==null?"var(--ink-faint)":p>=75?"var(--good)":p<=25?"var(--bad)":"var(--home)";const SITS=[["assisted","Jugada armada (con asistencia)"],["fast-break","Contraataque"],["corner","Córner"],["set-piece","Pelota parada"],["free-kick","Tiro libre"],["penalty","Penal"],["regular","Jugada individual"],["throw-in-set-piece","Lateral"]];const st={sit:"assisted",sitM:"xg",cat:"general",pos:"",eq:"",edad:"",modo:"rank",minJ:MINPCT,orden:"score",asc:false,buscar:""};const cumpleEdad=j=>!st.edad||(j.age!=null&&j.age<+st.edad);const equipos=[...new Map(JUG.map(j=>[j.ts,j.tn])).entries()].sort((a,b)=>a[1].localeCompare(b[1]));function puntajeCat(j,cat){if(!cat.keys)return j.score;const ps=cat.keys.map(k=>pct(j,k)).filter(p=>p!=null);if(ps.length<Math.ceil(cat.keys.length/2))return null;return Math.round(ps.reduce((a,b)=>a+b,0)/ps.length);}
function lista(){const cat=LIGA.categorias.find(c=>c.id===st.cat);let js=JUG.filter(j=>j.min>=st.minJ&&cat.pos.includes(j.pos)&&(!st.pos||j.pos===st.pos)&&(!st.eq||j.ts===st.eq)&&cumpleEdad(j));js=js.map(j=>({j,s:puntajeCat(j,cat)})).filter(o=>o.s!=null);js.sort((a,b)=>b.s-a.s||b.j.min-a.j.min);return{cat,js};}
function rankHTML(){const{cat,js}=lista(),top=js.slice(0,30);const claves=cat.keys||null;const filas=top.map((o,i)=>{const j=o.j,ks=claves||LIGA.porPos[j.pos].filter(k=>MET[k].dir!==0&&pct(j,k)!=null).sort((a,b)=>pct(j,b)-pct(j,a)).slice(0,3);const chips=ks.map(k=>`<span class="chip-m" data-t="${esc(MET[k].label)}: mejor que el ${pct(j,k)}% de su puesto"><i style="background:${colorPct(pct(j,k))}"></i>${esc(MET[k].label.replace(" por 90'","").replace(" (PAdj)",""))} <b>${fmt(k,val(j,k))}</b></span>`).join("");return`<a class="rank-fila" href="${R}${j.u}"><span class="n">${i+1}</span>
      <span class="quien"><b>${esc(j.name)}</b><small>${escudoChico(j.ts)}${esc(j.tn)} · ${POSN[j.pos]} · ${j.min}'</small></span>
      <span class="chips-m">${chips}</span>
      <span class="barra-pct" data-t="Puntaje contra los de su puesto"><i style="width:${o.s}%;background:${colorPct(o.s)}"></i><b>${o.s}</b></span></a>`;}).join("");const nota=cat.keys?`Promedio del percentil en: ${cat.keys.map(k=>MET[k].label).join(", ")}.`:"";return`<div class="card"><p class="adv-note" style="margin:0 0 12px">${esc(cat.desc)} ${esc(nota)} Entran jugadores con ${st.minJ}' o más${js.length?`(${js.length}en total)`:""}.</p>
    <div class="rank-lista">${filas || '<p class="muted">Ningún jugador cumple con los filtros.</p>'}</div></div>`;}
const COLS=[["score","Puntaje"],["age","Edad"],["rating","Nota"],["min","Min"],["g","Goles"],["a","Asist."],["xg","xG"],["xa","xA"],["sh","Remates"],["kp","P. clave"],["di","Dinamismo"],["goals90","Goles/90"],["npxg","npxG/90"],["xa90","xA/90"],["progP","P. prog./90"],["conduc","Cond./90"],["regG","Regates/90"],["tackW","Entradas"],["inter","Intercep."],["recup","Recup."],["duelPct","% duelos"],["pasePct","% pases"],["km","Km/90"]];function valorCol(j,c){if(c==="score"||c==="rating"||c==="min"||c==="di"||c==="age")return j[c];if(["g","a","xg","xa","sh","kp"].includes(c))return j.tot[c];const k=c==="xa90"?"xa":c;return KI[k]!=null?val(j,k):null;}
function fmtCol(j,c){const v=valorCol(j,c);if(v==null)return"–";if(["score","min","g","a","sh","kp","di","age"].includes(c))return String(Math.round(v));if(c==="rating"||c==="xg"||c==="xa")return v.toFixed(2);return KI[c==="xa90"?"xa":c]!=null?fmt(c==="xa90"?"xa":c,v):String(v);}
function tablaHTML(){let js=JUG.filter(j=>j.min>=st.minJ&&(!st.pos||j.pos===st.pos)&&(!st.eq||j.ts===st.eq)&&cumpleEdad(j));if(st.buscar){const q=st.buscar.toLowerCase();js=js.filter(j=>j.name.toLowerCase().includes(q));}
js.sort((a,b)=>{const va=valorCol(a,st.orden),vb=valorCol(b,st.orden);if(va==null&&vb==null)return 0;if(va==null)return 1;if(vb==null)return-1;return st.asc?va-vb:vb-va;});const cab=COLS.map(([c,l])=>`<th class="n ord ${st.orden===c?"act":""}" data-c="${c}">${l}${st.orden===c?(st.asc?" ▲":" ▼"):""}</th>`).join("");const filas=js.slice(0,300).map(j=>`<tr><td><a href="${R}${j.u}"><b>${esc(j.name)}</b></a></td><td>${escudoChico(j.ts)}${esc(j.tn)}</td><td>${POSA[j.pos]||j.pos}</td>${COLS.map(([c])=>`<td class="n ${st.orden===c?"act":""}">${fmtCol(j,c)}</td>`).join("")}</tr>`).join("");return`<div class="card table-scroll"><table class="tabla"><thead><tr><th>Jugador</th><th>Equipo</th><th>Pos</th>${cab}</tr></thead><tbody>${filas}</tbody></table>
    <p class="adv-note" style="margin-top:10px">Tocá el título de una columna para ordenar. Las métricas por 90 ya están ajustadas por minutos; las defensivas por posesión del rival (PAdj). ${js.length>300?"Se muestran los primeros 300.":""}</p></div>`;}
function sitHTML(){const idx=st.sitM==="g"?1:st.sitM==="sh"?0:2;let js=JUG.filter(j=>j.min>=st.minJ&&(!st.pos||j.pos===st.pos)&&(!st.eq||j.ts===st.eq)&&cumpleEdad(j)&&j.sit&&j.sit[st.sit]);js.sort((a,b)=>b.sit[st.sit][idx]-a.sit[st.sit][idx]||b.sit[st.sit][2]-a.sit[st.sit][2]);const filas=js.slice(0,30).map((j,i)=>{const x=j.sit[st.sit];return`<a class="rank-fila" href="${R}${j.u}"><span class="n">${i+1}</span><span class="quien"><b>${esc(j.name)}</b><small>${escudoChico(j.ts)}${esc(j.tn)} · ${POSN[j.pos]} · ${j.min}'</small></span>
      <span class="chips-m"><span class="chip-m">Remates <b>${x[0]}</b></span><span class="chip-m">Goles <b>${x[1]}</b></span><span class="chip-m">xG <b>${x[2].toFixed(2)}</b></span></span>
      <span class="barra-pct"><b style="float:none;display:block;text-align:right">${idx===2?x[2].toFixed(2):x[idx]}</b></span></a>`;}).join("");return`<div class="chips" style="margin-bottom:8px">${SITS.map(([k,l])=>`<span class="filter-chip ${st.sit===k?"active":""}"data-sit="${k}">${l}</span>`).join("")}</div>
   <div class="chips" style="margin-bottom:10px"><span class="muted" style="align-self:center;font-size:12.5px">Ordenar por:</span>${[["xg","xG"],["g","Goles"],["sh","Remates"]].map(([k,l])=>`<span class="filter-chip ${st.sitM===k?"active":""}"data-sitm="${k}">${l}</span>`).join("")}</div>
   <div class="card"><p class="adv-note" style="margin:0 0 12px">Remates, goles y xG de cada jugador según cómo se generó la jugada. "Jugada armada" es cuando un compañero le da el pase del remate; "individual" es sin asistencia. Con ${st.minJ}' o más${js.length?`(${js.length}jugadores)`:""}.</p><div class="rank-lista">${filas||'<p class="muted">Nadie cumple con los filtros.</p>'}</div></div>`;}
function catsHTML(){return`<div class="cat-grid">${LIGA.categorias.map(c=>`<button type="button"class="cat ${st.cat===c.id&&st.modo==="rank"?"act":""}"data-cat="${c.id}"><b>${esc(c.titulo)}</b><span>${esc(c.desc)}</span></button>`).join("")}</div>`;}
function filtrosActivos(){const chips=[];if(st.eq)chips.push(["eq","Equipo: "+esc(equipos.find(([s])=>s===st.eq)?.[1]||st.eq)]);if(st.pos)chips.push(["pos","Puesto: "+POSP[st.pos]]);if(st.edad)chips.push(["edad","Menores de "+st.edad]);if(!chips.length)return"";return`<div class="filtros-activos"><span>Mostrando solo</span>${chips.map(([k,l])=>`<span class="filtro-chip">${l}<button type="button"data-quitar="${k}"aria-label="Quitar filtro">×</button></span>`).join("")}<button type="button" class="link-quitar" data-quitar="todo">Quitar todos los filtros</button></div>`;}
function filtrosHTML(){return`${filtrosActivos()}<div class="filtros">
    <label>Puesto <select id="f-pos" class="${st.pos?"activo":""}"><option value="">Todos</option>${["F","M","D","G"].map(p=>`<option value="${p}"${st.pos===p?"selected":""}>${POSP[p]}</option>`).join("")}</select></label>
    <label>Equipo <select id="f-eq" class="${st.eq?"activo":""}"><option value="">Toda la liga</option>${equipos.map(([s,n])=>`<option value="${s}"${st.eq===s?"selected":""}>${esc(n)}</option>`).join("")}</select></label>
    <label>Minutos mínimos <select id="f-min">${[90,180,450,900,1350].map(m=>`<option value="${m}"${st.minJ===m?"selected":""}>${m}'</option>`).join("")}</select></label>
    <label>Edad <select id="f-edad" class="${st.edad?"activo":""}"><option value="">Todas</option>${[19,20,21,22,23,25].map(e=>`<option value="${e}"${st.edad===String(e)?"selected":""}>Sub-${e}</option>`).join("")}</select></label>
    ${st.modo==="tabla"?`<label>Nombre<input id="f-q"type="search"value="${esc(st.buscar)}"placeholder="filtrar…"></label>`:""}
    <div class="chips" style="margin-left:auto"><span class="filter-chip ${st.modo==="rank"?"active":""}" data-modo="rank">Rankings</span><span class="filter-chip ${st.modo==="sit"?"active":""}" data-modo="sit">Situaciones de gol</span><span class="filter-chip ${st.modo==="tabla"?"active":""}" data-modo="tabla">Tabla completa</span></div></div>`;}
function pintar(){const foco=document.activeElement&&document.activeElement.id;document.getElementById("lid").innerHTML=filtrosHTML()+(st.modo==="rank"?catsHTML()+rankHTML():st.modo==="sit"?sitHTML():tablaHTML());const q=e=>document.getElementById(e);q("f-pos").onchange=e=>{st.pos=e.target.value;pintar();};q("f-eq").onchange=e=>{st.eq=e.target.value;pintar();};q("f-min").onchange=e=>{st.minJ=+e.target.value;pintar();};q("f-edad").onchange=e=>{st.edad=e.target.value;pintar();};if(q("f-q")){q("f-q").oninput=e=>{st.buscar=e.target.value;const p=e.target.selectionStart;pintar();const n=q("f-q");n.focus();n.setSelectionRange(p,p);};}
document.querySelectorAll("[data-modo]").forEach(c=>c.onclick=()=>{st.modo=c.dataset.modo;pintar();});document.querySelectorAll("[data-sit]").forEach(c=>c.onclick=()=>{st.sit=c.dataset.sit;pintar();});document.querySelectorAll("[data-sitm]").forEach(c=>c.onclick=()=>{st.sitM=c.dataset.sitm;pintar();});document.querySelectorAll("[data-cat]").forEach(c=>c.onclick=()=>{st.cat=c.dataset.cat;st.modo="rank";pintar();});document.querySelectorAll("[data-quitar]").forEach(c=>c.onclick=()=>{const k=c.dataset.quitar;if(k==="todo"){st.eq="";st.pos="";st.edad="";}else st[k]="";pintar();});document.querySelectorAll("th.ord").forEach(c=>c.onclick=()=>{const k=c.dataset.c;if(st.orden===k)st.asc=!st.asc;else{st.orden=k;st.asc=k==="min"?false:false;}pintar();});}
const tip=document.createElement("div");tip.id="tip2";document.body.appendChild(tip);document.addEventListener("mousemove",e=>{const t=e.target.closest&&e.target.closest("[data-t]");if(!t){tip.style.opacity=0;return;}
tip.textContent=t.getAttribute("data-t");tip.style.opacity=1;tip.style.left=Math.min(window.innerWidth-320,e.clientX+14)+"px";tip.style.top=(e.clientY+16)+"px";});app.innerHTML=`<div class="sitio-nav"><a class="marca" href="${R}index.html"><img src="${R}favicon.png" alt="" class="marca-logo">Liga <b>Stats</b></a><a href="${R}index.html">Inicio</a><a href="${R}liga/index.html" class="act">Mejores jugadores</a><a href="${R}simulador/index.html">Simulador</a><div class="sp"></div><button type="button" class="tema-btn" aria-label="Cambiar entre modo claro y oscuro"></button><div class="buscador"></div></div>
  <div class="hero"><div class="hero-inner"><div class="hero-eyebrow">Liga Profesional</div><h1>Mejores jugadores</h1>
  <div class="subt"><span>${JUG.length} jugadores</span><span>${LIGA.params.partidos} partidos</span></div></div></div>
  <div class="wrap"><div id="lid"></div>
  <p class="adv-note" style="margin-top:28px">El puntaje compara a cada jugador solo con los de su mismo puesto (percentil 0-100). Es una guía, no un veredicto: con pocos minutos varía mucho.</p></div><footer>Liga Stats</footer>`;pintar();})();